name: Test on pr
on: 
    pull_request:
        branches: 
        #run when a pr is made (target must be master branch)
        - master
jobs:
    test:
        runs-on: ubuntu-latest    
        steps:
        - uses: actions/checkout@v1
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.201
        - name: Test with dotnet
          run:    dotnet test